### ISSUE TITLE
How to build this library

### ISSUE THREAD

**Issue by aliechti** [remotelock/react-week-scheduler#14]
Hi, I'm using webpack with typescript and have some problems.

```
error  in ./node_modules/@remotelock/react-week-scheduler/index.mjs

Can't import the named export 'useRef' from non EcmaScript module (only default export is available)
```
I tried to fix it with this (found here https://github.com/graphql/graphql-js/issues/1272):
```js
// webpack.config.js
{
  test: /\.mjs$/,
  include: /node_modules/,
  type: "javascript/auto",
}
```
Which fixed the build, but then I got another error in the browser:
```
Uncaught TypeError: Object(...) is not a function
    at TimeGridScheduler (index.mjs:1251)
```
![image](https://user-images.githubusercontent.com/10514993/65337170-f496a900-dbc7-11e9-99a4-b075ee19f0a0.png)

Do you have any hint what I should try to get it to work?

**Comment by forabi** [comment]
@thejahweh Hey Adrian! Thanks for opening this issue. We use this in production and we have the same webpack rule applied so I'm really surprised this does not work for you. Can you share more details on your setup? Maybe webpack config and package versions?

**Comment by aliechti** [comment]
Thanks, the information that you use it this way already and it works helped me allot. So I knew it wasn't the build process.

The problem was the incorrect react version, I've upgraded to `16.8.4` and now it works 👍

**Comment by forabi** [comment]
Glad it worked!
