### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by aliechti** [remotelock/react-week-scheduler#16]
Is it possible to use 24 hour format instead of am/pm?

**Comment by forabi** [comment]
You can provide a custom date-fns locale to the conext provider or replace
the whole time block component and render whatever text you like.

**Comment by vincentlunal** [comment]
Hi @forabi . First, thanks for you work.
Could you provide more details about the time block component ? I can't find it in your demo.
I changed the date-fns locale, and it only changes the name of the days, not the format. (I changed the locale to "fr", so it should be the 24h format).

**Comment by forabi** [comment]
You can copy paste EventContent from this repo's source code and change how
the times are formatted however you like, then pass in this component as
eventContentComponent prop to TimeGridScheduler

**Comment by vincentlunal** [comment]
Ok, but that's for the content of the selected hours.
I meant for the left side, where the hours are displayed.

**Comment by forabi** [comment]
I’m afraid that is not possible currently, the formats are hardcoded. Feel free to open a PR if you can help!
