### ISSUE TITLE
Schedule types, based on colours and labels

### ISSUE THREAD

**Issue by pimvanderheijden** [remotelock/react-week-scheduler#2]
Hello

This looks like a great module / fork. I'm considering to use it. Before I can make that choice, however, I'd   like to know if there's a way to create schedule types or whatever you want to call it.

For example, one blue schedule labelled "fishing" and one green schedule labelled "soccer".

Thanks in advance

**Comment by forabi** [comment]
Hey! Thanks for the interest.

This module is very new, released less than a month ago. It was designed with one lock access schedule in mind for use on `connect.remotelock.com`. However, there might come a use case in the near feature where we need to _display_ (not edit) two schedules (lock action, auto lock) on the same timegrid.

I wanted to focus on an MVP first but any contributions are welcome!

**Comment by pimvanderheijden** [comment]
Great. Thanks for letting me know!

**Comment by forabi** [comment]
@MidnightP Update: it's now possible to customize how each cell in the time grid is rendered by passing custom components as `eventRootComponent` and `eventContentComponent`. See the default implementation for an example: https://github.com/remotelock/react-week-scheduler/blob/master/src/components/DefaultEventRootComponent.tsx

With this, you can "fake" multiple schedules by passing a single, flattened schedule object and checking the range index of each date range in the custom component and render e.g. a different background color.

**Comment by pimvanderheijden** [comment]
Wow that sounds really cool! I switched over to a Vue library called [vue-cal](https://antoniandre.github.io/vue-cal/), since we're migrating in that direction anyway. We'll load in the Vue component in our React app.
