### ISSUE TITLE
Custom locale language not working

### ISSUE THREAD

**Issue by benoit-ctrl** [remotelock/react-week-scheduler#26]
Hello,

I tried to change the locale language from date-nfs and it did't work, I have fork the code sandbox from the README to having an example : https://codesandbox.io/s/react-week-scheduler-basic-demo-1eo2n?file=/src/index.js . 
Besides it's works at https://remotelock.github.io/react-week-scheduler/...
I have read the component source code but I did'nt find anything weird for know, may be I'm not using locale correctly ?

Thanks

**Comment by forabi** [comment]
https://github.com/remotelock/react-week-scheduler/blob/e447133f1778be9f0db42d7e1a2c4ef62f62f84e/demo/index.tsx#L333

**Comment by benoit-ctrl** [comment]
This is what I have done in the code sandbox but that did'nt work, can you look it please ?

Thanks

**Comment by forabi** [comment]
I think you need to use `date-fns` v1

**Comment by benoit-ctrl** [comment]
Indeed it was that, thanks ! 
May be it's will be useful to add this information in the README.

I'm eventually planning to add some little options to the scheduler in the next months, would you will able and disponible to check the PRs and merge them when the time comes ?

**Comment by forabi** [comment]
> would you will able and disponible to check the PRs and merge them when the time comes ?

Hopefully yes
