### ISSUE TITLE
Can't import the named export 'createContext'.

### ISSUE THREAD

**Issue by enessahin1** [remotelock/react-week-scheduler#39]
I'm getting this error, can you help me?

./node_modules/@remotelock/react-week-scheduler/index.mjs
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)

**Comment by benoit-ctrl** [comment]
Hello, if you're are using create-react-app please see https://github.com/remotelock/react-week-scheduler/issues/7#issuecomment-664485857 there is a fix !

**Comment by enessahin1** [comment]
thank you so much!!
