### ISSUE TITLE
Deleting Scheduler

### ISSUE THREAD

**Issue by enessahin1** [remotelock/react-week-scheduler#40]
After creating a schedule, I hover on it with the mouse, but I can't see a field to delete. The program can be created but not delete. What should I do to delete it like in the demo?

**Comment by forabi** [comment]
https://github.com/remotelock/react-week-scheduler/issues/28#issuecomment-679896259

Please have a look at the existing issues before creating a new one

**Comment by enessahin1** [comment]
thanks a lot.

**Comment by liew312** [comment]
> thanks a lot.

Hi, did you find a way to do it?
